name: New Feature
description: New Feature to the system
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Bisuness File 
      description: "The name of the bsuiness file in the application layer"
      placeholder: "Get .... _CMPLX"
    validations:
      required: true 
